POST http://localhost:3333/subscriptions
Content-Type: application/json

{
  "name": "Usuários Indicados 6",
  "email": "indicados6@gmail.com.br",
  "referrer": "fe855ce5-1b09-4e6b-b5fb-ee8d6f25e3eb"
}

###

GET http://localhost:3333/invites/1e7db060-b8ef-4dd9-8a4f-4e66e1462e8e

###

GET http://localhost:3333/subscribers/1e7db060-b8ef-4dd9-8a4f-4e66e1462e8e/ranking/clicks

###

GET http://localhost:3333/subscribers/1e7db060-b8ef-4dd9-8a4f-4e66e1462e8e/ranking/count

###

GET http://localhost:3333/subscribers/1e7db060-b8ef-4dd9-8a4f-4e66e1462e8e/ranking/position

###

GET http://localhost:3333/ranking