POST http://localhost:3333/subscriptions
Content-Type: application/json

{
  "name": "Teste Brazuna",
  "email": "teste@teste.com.br",
  "referrer": "86b2c84c-5d9b-4262-bc23-609f4a507d5b"
}

###
GET http://localhost:3333/invites/86b2c84c-5d9b-4262-bc23-609f4a507d5b

###
GET http://localhost:3333/subscribers/86b2c84c-5d9b-4262-bc23-609f4a507d5b/ranking/clicks

###
GET http://localhost:3333/subscribers/86b2c84c-5d9b-4262-bc23-609f4a507d5b/ranking/count